/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvalRouteImport } from './routes/eval'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as ApiGenerateEditsRouteImport } from './routes/api/generate-edits'
import { Route as SkusIndexRouteImport } from './routes/skus/index'
import { Route as SkusSkuIdRouteImport } from './routes/skus/$skuId'
import { Route as SkusSkuIdSummaryRouteImport } from './routes/skus/$skuId_.summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalRoute = EvalRouteImport.update({
  id: '/eval',
  path: '/eval',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateEditsRoute = ApiGenerateEditsRouteImport.update({
  id: '/api/generate-edits',
  path: '/api/generate-edits',
  getParentRoute: () => rootRouteImport,
} as any)
const SkusIndexRoute = SkusIndexRouteImport.update({
  id: '/skus/',
  path: '/skus/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkusSkuIdRoute = SkusSkuIdRouteImport.update({
  id: '/skus/$skuId',
  path: '/skus/$skuId',
  getParentRoute: () => rootRouteImport,
} as any)
const SkusSkuIdSummaryRoute = SkusSkuIdSummaryRouteImport.update({
  id: '/skus/$skuId_/summary',
  path: '/skus/$skuId/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eval': typeof EvalRoute
  '/guidelines': typeof GuidelinesRoute
  '/api/generate-edits': typeof ApiGenerateEditsRoute
  '/skus/$skuId': typeof SkusSkuIdRoute
  '/skus/': typeof SkusIndexRoute
  '/skus/$skuId/summary': typeof SkusSkuIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eval': typeof EvalRoute
  '/guidelines': typeof GuidelinesRoute
  '/api/generate-edits': typeof ApiGenerateEditsRoute
  '/skus/$skuId': typeof SkusSkuIdRoute
  '/skus': typeof SkusIndexRoute
  '/skus/$skuId/summary': typeof SkusSkuIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eval': typeof EvalRoute
  '/guidelines': typeof GuidelinesRoute
  '/api/generate-edits': typeof ApiGenerateEditsRoute
  '/skus/$skuId': typeof SkusSkuIdRoute
  '/skus/': typeof SkusIndexRoute
  '/skus/$skuId_/summary': typeof SkusSkuIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eval'
    | '/guidelines'
    | '/api/generate-edits'
    | '/skus/$skuId'
    | '/skus/'
    | '/skus/$skuId/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eval'
    | '/guidelines'
    | '/api/generate-edits'
    | '/skus/$skuId'
    | '/skus'
    | '/skus/$skuId/summary'
  id:
    | '__root__'
    | '/'
    | '/eval'
    | '/guidelines'
    | '/api/generate-edits'
    | '/skus/$skuId'
    | '/skus/'
    | '/skus/$skuId_/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvalRoute: typeof EvalRoute
  GuidelinesRoute: typeof GuidelinesRoute
  ApiGenerateEditsRoute: typeof ApiGenerateEditsRoute
  SkusSkuIdRoute: typeof SkusSkuIdRoute
  SkusIndexRoute: typeof SkusIndexRoute
  SkusSkuIdSummaryRoute: typeof SkusSkuIdSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval': {
      id: '/eval'
      path: '/eval'
      fullPath: '/eval'
      preLoaderRoute: typeof EvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-edits': {
      id: '/api/generate-edits'
      path: '/api/generate-edits'
      fullPath: '/api/generate-edits'
      preLoaderRoute: typeof ApiGenerateEditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skus/': {
      id: '/skus/'
      path: '/skus'
      fullPath: '/skus/'
      preLoaderRoute: typeof SkusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skus/$skuId': {
      id: '/skus/$skuId'
      path: '/skus/$skuId'
      fullPath: '/skus/$skuId'
      preLoaderRoute: typeof SkusSkuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skus/$skuId_/summary': {
      id: '/skus/$skuId_/summary'
      path: '/skus/$skuId/summary'
      fullPath: '/skus/$skuId/summary'
      preLoaderRoute: typeof SkusSkuIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvalRoute: EvalRoute,
  GuidelinesRoute: GuidelinesRoute,
  ApiGenerateEditsRoute: ApiGenerateEditsRoute,
  SkusSkuIdRoute: SkusSkuIdRoute,
  SkusIndexRoute: SkusIndexRoute,
  SkusSkuIdSummaryRoute: SkusSkuIdSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
